"""Create unit and room tables

Revision ID: b816ee70ec83
Revises: 
Create Date: 2016-11-11 16:22:18.856932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b816ee70ec83'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('unit',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.BigInteger(), server_default=sa.text('cast(EXTRACT(EPOCH FROM NOW()) as BIGINT)'), nullable=True),
    sa.Column('updated_at', sa.BigInteger(), server_default=sa.text('cast(EXTRACT(EPOCH FROM NOW()) as BIGINT)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('room',
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('length', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.BigInteger(), server_default=sa.text('cast(EXTRACT(EPOCH FROM NOW()) as BIGINT)'), nullable=True),
    sa.Column('updated_at', sa.BigInteger(), server_default=sa.text('cast(EXTRACT(EPOCH FROM NOW()) as BIGINT)'), nullable=True),
    sa.ForeignKeyConstraint(['unit_id'], ['unit.id'], name='unit_id__unit_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('room')
    op.drop_table('unit')
    ### end Alembic commands ###
